import { PrismaClient } from '../src/generated/prisma/client.js';

const prisma = new PrismaClient();

const classifications = [
    {
        name: 'general',
        emoji: '🌐',
        index: 0,
        nameZHCN: '综合类',
        nameZHTW: '綜合類',
        nameENUS: 'General',
        nameESES: 'General',
        nameFRFR: 'Général',
        nameRURU: 'Общий',
        nameJAJP: '総合',
        nameDEDE: 'Allgemein',
        namePTBR: 'Geral',
        nameKOKR: '종합',
    },
    {
        name: 'technology_creation',
        emoji: '🛠️',
        index: 1,
        nameZHCN: '技术与创作',
        nameZHTW: '技術與創作',
        nameENUS: 'Technology & Creation',
        nameESES: 'Tecnología y Creación',
        nameFRFR: 'Technologie et Création',
        nameRURU: 'Технологии и Творчество',
        nameJAJP: 'テクノロジーと創作',
        nameDEDE: 'Technologie & Kreation',
        namePTBR: 'Tecnologia e Criação',
        nameKOKR: '기술 및 창작',
    },
    {
        name: 'learning_education',
        emoji: '📚',
        index: 2,
        nameZHCN: '学习与教育',
        nameZHTW: '學習與教育',
        nameENUS: 'Learning & Education',
        nameESES: 'Aprendizaje y Educación',
        nameFRFR: 'Apprentissage et Éducation',
        nameRURU: 'Обучение и Образование',
        nameJAJP: '学習と教育',
        nameDEDE: 'Lernen & Bildung',
        namePTBR: 'Aprendizado e Educação',
        nameKOKR: '학습 및 교육',
    },
    {
        name: 'entertainment_leisure',
        emoji: '🎬',
        index: 3,
        nameZHCN: '娱乐休闲',
        nameZHTW: '娛樂休閒',
        nameENUS: 'Entertainment & Leisure',
        nameESES: 'Entretenimiento y Ocio',
        nameFRFR: 'Divertissement et Loisirs',
        nameRURU: 'Развлечения и Досуг',
        nameJAJP: 'エンターテイメントとレジャー',
        nameDEDE: 'Unterhaltung & Freizeit',
        namePTBR: 'Entretenimento e Lazer',
        nameKOKR: '엔터테인먼트 및 레저',
    },
    {
        name: 'lifestyle',
        emoji: '🏖️',
        index: 4,
        nameZHCN: '生活方式',
        nameZHTW: '生活方式',
        nameENUS: 'Lifestyle',
        nameESES: 'Estilo de Vida',
        nameFRFR: 'Style de Vie',
        nameRURU: 'Образ Жизни',
        nameJAJP: 'ライフスタイル',
        nameDEDE: 'Lebensstil',
        namePTBR: 'Estilo de Vida',
        nameKOKR: '라이프스타일',
    },
    {
        name: 'career_development',
        emoji: '💼',
        index: 5,
        nameZHCN: '职业发展',
        nameZHTW: '職業發展',
        nameENUS: 'Career Development',
        nameESES: 'Desarrollo Profesional',
        nameFRFR: 'Développement de Carrière',
        nameRURU: 'Карьерное Развитие',
        nameJAJP: 'キャリア開発',
        nameDEDE: 'Karriereentwicklung',
        namePTBR: 'Desenvolvimento Profissional',
        nameKOKR: '경력 개발',
    },
    {
        name: 'arts_humanities',
        emoji: '🏛️',
        index: 6,
        nameZHCN: '人文艺术',
        nameZHTW: '人文藝術',
        nameENUS: 'Arts & Humanities',
        nameESES: 'Artes y Humanidades',
        nameFRFR: 'Arts et Sciences Humaines',
        nameRURU: 'Искусство и Гуманитарные Науки',
        nameJAJP: '人文科学と芸術',
        nameDEDE: 'Kunst & Geisteswissenschaften',
        namePTBR: 'Artes e Humanidades',
        nameKOKR: '예술 및 인문학',
    },
    {
        name: 'science_nature',
        emoji: '🔭',
        index: 7,
        nameZHCN: '科学与自然',
        nameZHTW: '科學與自然',
        nameENUS: 'Science & Nature',
        nameESES: 'Ciencia y Naturaleza',
        nameFRFR: 'Science et Nature',
        nameRURU: 'Наука и Природа',
        nameJAJP: '科学と自然',
        nameDEDE: 'Wissenschaft & Natur',
        namePTBR: 'Ciência e Natureza',
        nameKOKR: '과학 및 자연',
    },
    {
        name: 'health_wellness',
        emoji: '❤️‍🩹',
        index: 8,
        nameZHCN: '健康与保健',
        nameZHTW: '健康與保健',
        nameENUS: 'Health & Wellness',
        nameESES: 'Salud y Bienestar',
        nameFRFR: 'Santé et Bien-être',
        nameRURU: 'Здоровье и Благополучие',
        nameJAJP: '健康とウェルネス',
        nameDEDE: 'Gesundheit & Wellness',
        namePTBR: 'Saúde e Bem-estar',
        nameKOKR: '건강 및 웰빙',
    },
    {
        name: 'sports_recreation',
        emoji: '⚽',
        index: 9,
        nameZHCN: '体育与运动',
        nameZHTW: '體育與運動',
        nameENUS: 'Sports & Recreation',
        nameESES: 'Deportes y Recreación',
        nameFRFR: 'Sports et Loisirs',
        nameRURU: 'Спорт и Отдых',
        nameJAJP: 'スポーツとレクリエーション',
        nameDEDE: 'Sport & Erholung',
        namePTBR: 'Esportes e Recreação',
        nameKOKR: '스포츠 및 레크리에이션',
    },
    {
        name: 'hobbies_crafts',
        emoji: '🎨',
        index: 10,
        nameZHCN: '爱好与手工艺',
        nameZHTW: '愛好與手工藝',
        nameENUS: 'Hobbies & Crafts',
        nameESES: 'Aficiones y Manualidades',
        nameFRFR: 'Passe-temps et Artisanat',
        nameRURU: 'Хобби и Ремесла',
        nameJAJP: '趣味と工芸',
        nameDEDE: 'Hobbys & Handwerk',
        namePTBR: 'Hobbies e Artesanato',
        nameKOKR: '취미 및 공예',
    },
    {
        name: 'society_culture',
        emoji: '🌍',
        index: 11,
        nameZHCN: '社会与文化',
        nameZHTW: '社會與文化',
        nameENUS: 'Society & Culture',
        nameESES: 'Sociedad y Cultura',
        nameFRFR: 'Société et Culture',
        nameRURU: 'Общество и Культура',
        nameJAJP: '社会と文化',
        nameDEDE: 'Gesellschaft & Kultur',
        namePTBR: 'Sociedade e Cultura',
        nameKOKR: '사회 및 문화',
    },
];

const topics = [
    // ===================================
    // 综合类 (General)
    // ===================================
    {
        name: 'current_events',
        emoji: '📰',
        index: 0,
        classificationName: 'general',
        nameZHCN: '时事热点',
        nameZHTW: '時事熱點',
        nameENUS: 'Current Events',
        nameESES: 'Actualidad',
        nameFRFR: 'Actualités',
        nameRURU: 'Актуальные События',
        nameJAJP: '時事',
        nameDEDE: 'Aktuelle Ereignisse',
        namePTBR: 'Eventos Atuais',
        nameKOKR: '시사',
    },
    {
        name: 'casual_chat',
        emoji: '💬',
        index: 1,
        classificationName: 'general',
        nameZHCN: '灌水闲聊',
        nameZHTW: '灌水閒聊',
        nameENUS: 'Casual Chat',
        nameESES: 'Charla Casual',
        nameFRFR: 'Discussion Décontractée',
        nameRURU: 'Свободное Общение',
        nameJAJP: '雑談',
        nameDEDE: 'Lockerer Chat',
        namePTBR: 'Bate-papo Casual',
        nameKOKR: '자유 대화',
    },
    {
        name: 'new_member_intro',
        emoji: '🤝',
        index: 2,
        classificationName: 'general',
        nameZHCN: '新人报到',
        nameZHTW: '新人報到',
        nameENUS: 'New Member Introduction',
        nameESES: 'Presentación de Nuevos Miembros',
        nameFRFR: 'Présentation des Nouveaux Membres',
        nameRURU: 'Знакомство Новых Участников',
        nameJAJP: '新人紹介',
        nameDEDE: 'Vorstellung Neuer Mitglieder',
        namePTBR: 'Apresentação de Novos Membros',
        nameKOKR: '신규 회원 소개',
    },
    {
        name: 'jokes_memes',
        emoji: '😂',
        index: 3,
        classificationName: 'general',
        nameZHCN: '笑话与梗图',
        nameZHTW: '笑話與梗圖',
        nameENUS: 'Jokes & Memes',
        nameESES: 'Chistes y Memes',
        nameFRFR: 'Blagues et Mèmes',
        nameRURU: 'Шутки и Мемы',
        nameJAJP: 'ジョークとミーム',
        nameDEDE: 'Witze & Memes',
        namePTBR: 'Piadas e Memes',
        nameKOKR: '농담 및 밈',
    },
    {
        name: 'site_feedback',
        emoji: '📝',
        index: 4,
        classificationName: 'general',
        nameZHCN: '站务与反馈',
        nameZHTW: '站務與反饋',
        nameENUS: 'Site Feedback',
        nameESES: 'Sugerencias del Sitio',
        nameFRFR: 'Commentaires sur le Site',
        nameRURU: 'Обратная Связь по Сайту',
        nameJAJP: 'サイトへのフィードバック',
        nameDEDE: 'Website-Feedback',
        namePTBR: 'Feedback do Site',
        nameKOKR: '사이트 피드백',
    },
    {
        name: 'polls_surveys',
        emoji: '📊',
        index: 5,
        classificationName: 'general',
        nameZHCN: '投票与调查',
        nameZHTW: '投票與調查',
        nameENUS: 'Polls & Surveys',
        nameESES: 'Encuestas y Sondeos',
        nameFRFR: 'Sondages et Enquêtes',
        nameRURU: 'Опросы и Голосования',
        nameJAJP: '投票とアンケート',
        nameDEDE: 'Umfragen & Erhebungen',
        namePTBR: 'Enquetes e Pesquisas',
        nameKOKR: '투표 및 설문조사',
    },

    // ===================================
    // 技术与创作 (Technology & Creation)
    // ===================================
    {
        name: 'pc_building_modding',
        emoji: '🔩',
        index: 0,
        classificationName: 'technology_creation',
        nameZHCN: '电脑DIY与改装',
        nameZHTW: '電腦DIY與改裝',
        nameENUS: 'PC Building & Modding',
        nameESES: 'Montaje y Modding de PC',
        nameFRFR: 'Montage et Modding de PC',
        nameRURU: 'Сборка и Моддинг ПК',
        nameJAJP: 'PC自作と改造',
        nameDEDE: 'PC-Bau & Modding',
        namePTBR: 'Montagem e Modding de PC',
        nameKOKR: 'PC 조립 및 모딩',
    },
    {
        name: 'digital_hardware',
        emoji: '🖥️',
        index: 1,
        classificationName: 'technology_creation',
        nameZHCN: '数码硬件',
        nameZHTW: '數碼硬件',
        nameENUS: 'Digital Hardware',
        nameESES: 'Hardware Digital',
        nameFRFR: 'Matériel Numérique',
        nameRURU: 'Цифровое Оборудование',
        nameJAJP: 'デジタルハードウェア',
        nameDEDE: 'Digitale Hardware',
        namePTBR: 'Hardware Digital',
        nameKOKR: '디지털 하드웨어',
    },
    {
        name: 'mobile_apps',
        emoji: '📱',
        index: 2,
        classificationName: 'technology_creation',
        nameZHCN: '手机与APP',
        nameZHTW: '手機與APP',
        nameENUS: 'Mobile & Apps',
        nameESES: 'Móvil y Aplicaciones',
        nameFRFR: 'Mobile et Applications',
        nameRURU: 'Мобильные устройства и Приложения',
        nameJAJP: 'モバイルとアプリ',
        nameDEDE: 'Mobil & Apps',
        namePTBR: 'Mobile e Apps',
        nameKOKR: '모바일 및 앱',
    },
    {
        name: 'programming_dev',
        emoji: '💻',
        index: 3,
        classificationName: 'technology_creation',
        nameZHCN: '编程与开发',
        nameZHTW: '編程與開發',
        nameENUS: 'Programming & Development',
        nameESES: 'Programación y Desarrollo',
        nameFRFR: 'Programmation et Développement',
        nameRURU: 'Программирование и Разработка',
        nameJAJP: 'プログラミングと開発',
        nameDEDE: 'Programmierung & Entwicklung',
        namePTBR: 'Programação e Desenvolvimento',
        nameKOKR: '프로그래밍 및 개발',
    },
    {
        name: 'ai_machine_learning',
        emoji: '🤖',
        index: 4,
        classificationName: 'technology_creation',
        nameZHCN: 'AI 与机器学习',
        nameZHTW: 'AI 與機器學習',
        nameENUS: 'AI & Machine Learning',
        nameESES: 'IA y Aprendizaje Automático',
        nameFRFR: 'IA et Apprentissage Automatique',
        nameRURU: 'ИИ и Машинное Обучение',
        nameJAJP: 'AIと機械学習',
        nameDEDE: 'KI & Maschinelles Lernen',
        namePTBR: 'IA e Aprendizado de Máquina',
        nameKOKR: 'AI 및 머신 러닝',
    },
    {
        name: 'game_development',
        emoji: '🕹️',
        index: 5,
        classificationName: 'technology_creation',
        nameZHCN: '游戏开发',
        nameZHTW: '遊戲開發',
        nameENUS: 'Game Development',
        nameESES: 'Desarrollo de Videojuegos',
        nameFRFR: 'Développement de Jeux',
        nameRURU: 'Разработка Игр',
        nameJAJP: 'ゲーム開発',
        nameDEDE: 'Spieleentwicklung',
        namePTBR: 'Desenvolvimento de Jogos',
        nameKOKR: '게임 개발',
    },
    {
        name: 'original_writing',
        emoji: '✍️',
        index: 6,
        classificationName: 'technology_creation',
        nameZHCN: '原创写作',
        nameZHTW: '原創寫作',
        nameENUS: 'Original Writing',
        nameESES: 'Escritura Original',
        nameFRFR: 'Écriture Originale',
        nameRURU: 'Оригинальное Письмо',
        nameJAJP: 'オリジナル執筆',
        nameDEDE: 'Originales Schreiben',
        namePTBR: 'Escrita Original',
        nameKOKR: '창작 글쓰기',
    },
    {
        name: 'design_painting',
        emoji: '🎨',
        index: 7,
        classificationName: 'technology_creation',
        nameZHCN: '设计与绘画',
        nameZHTW: '設計與繪畫',
        nameENUS: 'Design & Painting',
        nameESES: 'Diseño y Pintura',
        nameFRFR: 'Design et Peinture',
        nameRURU: 'Дизайн и Живопись',
        nameJAJP: 'デザインと絵画',
        nameDEDE: 'Design & Malerei',
        namePTBR: 'Design e Pintura',
        nameKOKR: '디자인 및 그림',
    },
    {
        name: 'video_audio_production',
        emoji: '🎥',
        index: 8,
        classificationName: 'technology_creation',
        nameZHCN: '影音制作',
        nameZHTW: '影音製作',
        nameENUS: 'Video & Audio Production',
        nameESES: 'Producción de Vídeo y Audio',
        nameFRFR: 'Production Vidéo et Audio',
        nameRURU: 'Производство Видео и Аудио',
        nameJAJP: '映像・音声制作',
        nameDEDE: 'Video- & Audioproduktion',
        namePTBR: 'Produção de Vídeo e Áudio',
        nameKOKR: '영상 및 음향 제작',
    },
    {
        name: 'blockchain_crypto',
        emoji: '⛓️',
        index: 9,
        classificationName: 'technology_creation',
        nameZHCN: '区块链与加密货币',
        nameZHTW: '區塊鏈與加密貨幣',
        nameENUS: 'Blockchain & Crypto',
        nameESES: 'Blockchain y Criptomonedas',
        nameFRFR: 'Blockchain et Cryptomonnaies',
        nameRURU: 'Блокчейн и Криптовалюты',
        nameJAJP: 'ブロックチェーンと暗号資産',
        nameDEDE: 'Blockchain & Krypto',
        namePTBR: 'Blockchain e Criptomoedas',
        nameKOKR: '블록체인 및 암호화폐',
    },
    {
        name: '3d_printing_modeling',
        emoji: '🧊',
        index: 10,
        classificationName: 'technology_creation',
        nameZHCN: '3D打印与建模',
        nameZHTW: '3D列印與建模',
        nameENUS: '3D Printing & Modeling',
        nameESES: 'Impresión y Modelado 3D',
        nameFRFR: 'Impression et Modélisation 3D',
        nameRURU: '3D-печать и Моделирование',
        nameJAJP: '3Dプリントとモデリング',
        nameDEDE: '3D-Druck & Modellierung',
        namePTBR: 'Impressão e Modelagem 3D',
        nameKOKR: '3D 프린팅 및 모델링',
    },
    {
        name: 'robotics_automation',
        emoji: '🦾',
        index: 11,
        classificationName: 'technology_creation',
        nameZHCN: '机器人与自动化',
        nameZHTW: '機器人與自動化',
        nameENUS: 'Robotics & Automation',
        nameESES: 'Robótica y Automatización',
        nameFRFR: 'Robotique et Automatisation',
        nameRURU: 'Робототехника и Автоматизация',
        nameJAJP: 'ロボット工学と自動化',
        nameDEDE: 'Robotik & Automatisierung',
        namePTBR: 'Robótica e Automação',
        nameKOKR: '로봇 공학 및 자동화',
    },

    // ===================================
    // 学习与教育 (Learning & Education)
    // ===================================
    {
        name: 'academic_exchange',
        emoji: '📘',
        index: 0,
        classificationName: 'learning_education',
        nameZHCN: '学术交流',
        nameZHTW: '學術交流',
        nameENUS: 'Academic Exchange',
        nameESES: 'Intercambio Académico',
        nameFRFR: 'Échange Académique',
        nameRURU: 'Академический Обмен',
        nameJAJP: '学術交流',
        nameDEDE: 'Akademischer Austausch',
        namePTBR: 'Intercâmbio Acadêmico',
        nameKOKR: '학술 교류',
    },
    {
        name: 'study_skills',
        emoji: '🧠',
        index: 1,
        classificationName: 'learning_education',
        nameZHCN: '学习技巧',
        nameZHTW: '學習技巧',
        nameENUS: 'Study Skills',
        nameESES: 'Técnicas de Estudio',
        nameFRFR: "Techniques d'Étude",
        nameRURU: 'Навыки Обучения',
        nameJAJP: '学習スキル',
        nameDEDE: 'Lerntechniken',
        namePTBR: 'Técnicas de Estudo',
        nameKOKR: '학습 기법',
    },
    {
        name: 'language_learning',
        emoji: '🗣️',
        index: 2,
        classificationName: 'learning_education',
        nameZHCN: '语言学习',
        nameZHTW: '語言學習',
        nameENUS: 'Language Learning',
        nameESES: 'Aprendizaje de Idiomas',
        nameFRFR: 'Apprentissage des Langues',
        nameRURU: 'Изучение Языков',
        nameJAJP: '言語学習',
        nameDEDE: 'Sprachenlernen',
        namePTBR: 'Aprendizado de Idiomas',
        nameKOKR: '언어 학습',
    },
    {
        name: 'history_archeology',
        emoji: '🏺',
        index: 3,
        classificationName: 'learning_education',
        nameZHCN: '历史与考古',
        nameZHTW: '歷史與考古',
        nameENUS: 'History & Archeology',
        nameESES: 'Historia y Arqueología',
        nameFRFR: 'Histoire et Archéologie',
        nameRURU: 'История и Археология',
        nameJAJP: '歴史と考古学',
        nameDEDE: 'Geschichte & Archäologie',
        namePTBR: 'História e Arqueologia',
        nameKOKR: '역사 및 고고학',
    },
    {
        name: 'philosophy_psychology',
        emoji: '🤔',
        index: 4,
        classificationName: 'learning_education',
        nameZHCN: '哲学与心理学',
        nameZHTW: '哲學與心理學',
        nameENUS: 'Philosophy & Psychology',
        nameESES: 'Filosofía y Psicología',
        nameFRFR: 'Philosophie et Psychologie',
        nameRURU: 'Философия и Психология',
        nameJAJP: '哲学と心理学',
        nameDEDE: 'Philosophie & Psychologie',
        namePTBR: 'Filosofia e Psicologia',
        nameKOKR: '철학 및 심리학',
    },
    {
        name: 'economics_business',
        emoji: '💹',
        index: 5,
        classificationName: 'learning_education',
        nameZHCN: '经济与商业',
        nameZHTW: '經濟與商業',
        nameENUS: 'Economics & Business',
        nameESES: 'Economía y Negocios',
        nameFRFR: 'Économie et Commerce',
        nameRURU: 'Экономика и Бизнес',
        nameJAJP: '経済学とビジネス',
        nameDEDE: 'Wirtschaft & Business',
        namePTBR: 'Economia e Negócios',
        nameKOKR: '경제 및 비즈니스',
    },
    {
        name: 'law_studies',
        emoji: '⚖️',
        index: 6,
        classificationName: 'learning_education',
        nameZHCN: '法律学习',
        nameZHTW: '法律學習',
        nameENUS: 'Law Studies',
        nameESES: 'Estudios de Derecho',
        nameFRFR: 'Études de Droit',
        nameRURU: 'Юридические Исследования',
        nameJAJP: '法学',
        nameDEDE: 'Rechtswissenschaften',
        namePTBR: 'Estudos Jurídicos',
        nameKOKR: '법학',
    },
    {
        name: 'medical_studies',
        emoji: '🩺',
        index: 7,
        classificationName: 'learning_education',
        nameZHCN: '医学学习',
        nameZHTW: '醫學學習',
        nameENUS: 'Medical Studies',
        nameESES: 'Estudios Médicos',
        nameFRFR: 'Études de Médecine',
        nameRURU: 'Медицинские Исследования',
        nameJAJP: '医学',
        nameDEDE: 'Medizinstudium',
        namePTBR: 'Estudos Médicos',
        nameKOKR: '의학',
    },

    // ===================================
    // 娱乐休闲 (Entertainment & Leisure)
    // ===================================
    {
        name: 'gaming_discussion',
        emoji: '🎮',
        index: 0,
        classificationName: 'entertainment_leisure',
        nameZHCN: '游戏讨论',
        nameZHTW: '遊戲討論',
        nameENUS: 'Gaming Discussion',
        nameESES: 'Discusión de Juegos',
        nameFRFR: 'Discussion Jeux',
        nameRURU: 'Обсуждение Игр',
        nameJAJP: 'ゲーム議論',
        nameDEDE: 'Spiele-Diskussion',
        namePTBR: 'Discussão de Jogos',
        nameKOKR: '게임 토론',
    },
    {
        name: 'movies_tv',
        emoji: '🎬',
        index: 1,
        classificationName: 'entertainment_leisure',
        nameZHCN: '影视剧集',
        nameZHTW: '影視劇集',
        nameENUS: 'Movies & TV Shows',
        nameESES: 'Películas y Series',
        nameFRFR: 'Films et Séries',
        nameRURU: 'Фильмы и Сериалы',
        nameJAJP: '映画とテレビ番組',
        nameDEDE: 'Filme & TV-Shows',
        namePTBR: 'Filmes e Séries',
        nameKOKR: '영화 및 TV 프로그램',
    },
    {
        name: 'music_sharing',
        emoji: '🎵',
        index: 2,
        classificationName: 'entertainment_leisure',
        nameZHCN: '音乐分享',
        nameZHTW: '音樂分享',
        nameENUS: 'Music Sharing',
        nameESES: 'Compartir Música',
        nameFRFR: 'Partage Musical',
        nameRURU: 'Музыкальный Обмен',
        nameJAJP: '音楽シェア',
        nameDEDE: 'Musik-Sharing',
        namePTBR: 'Compartilhamento Musical',
        nameKOKR: '음악 공유',
    },
    {
        name: 'photography_exchange',
        emoji: '📷',
        index: 3,
        classificationName: 'entertainment_leisure',
        nameZHCN: '摄影交流',
        nameZHTW: '攝影交流',
        nameENUS: 'Photography Exchange',
        nameESES: 'Intercambio Fotográfico',
        nameFRFR: 'Échange Photographique',
        nameRURU: 'Фотографический Обмен',
        nameJAJP: '写真交流',
        nameDEDE: 'Fotografie-Austausch',
        namePTBR: 'Intercâmbio Fotográfico',
        nameKOKR: '사진 교류',
    },
    {
        name: 'novels_comics',
        emoji: '📚',
        index: 4,
        classificationName: 'entertainment_leisure',
        nameZHCN: '小说漫画',
        nameZHTW: '小說漫畫',
        nameENUS: 'Novels & Comics',
        nameESES: 'Novelas y Cómics',
        nameFRFR: 'Romans et BD',
        nameRURU: 'Романы и Комиксы',
        nameJAJP: '小説と漫画',
        nameDEDE: 'Romane & Comics',
        namePTBR: 'Romances e Quadrinhos',
        nameKOKR: '소설 및 만화',
    },
    {
        name: 'anime_manga_world',
        emoji: '🎌',
        index: 5,
        classificationName: 'entertainment_leisure',
        nameZHCN: '二次元天地',
        nameZHTW: '二次元天地',
        nameENUS: 'Anime & Manga World',
        nameESES: 'Mundo del Anime y Manga',
        nameFRFR: "Monde de l'Anime et du Manga",
        nameRURU: 'Мир Аниме и Манги',
        nameJAJP: 'アニメとマンガの世界',
        nameDEDE: 'Anime & Manga Welt',
        namePTBR: 'Mundo do Anime e Mangá',
        nameKOKR: '애니메이션 및 만화 세계',
    },
    {
        name: 'board_games_trpg',
        emoji: '🎲',
        index: 6,
        classificationName: 'entertainment_leisure',
        nameZHCN: '桌游与跑团',
        nameZHTW: '桌遊與跑團',
        nameENUS: 'Board Games & TRPG',
        nameESES: 'Juegos de Mesa y TRPG',
        nameFRFR: 'Jeux de Société et JDR',
        nameRURU: 'Настольные Игры и НРИ',
        nameJAJP: 'ボードゲームとTRPG',
        nameDEDE: 'Brettspiele & TRPG',
        namePTBR: 'Jogos de Tabuleiro e TRPG',
        nameKOKR: '보드게임 및 TRPG',
    },
    {
        name: 'celebrity_pop_culture',
        emoji: '🌟',
        index: 7,
        classificationName: 'entertainment_leisure',
        nameZHCN: '明星与流行文化',
        nameZHTW: '明星與流行文化',
        nameENUS: 'Celebrity & Pop Culture',
        nameESES: 'Celebridades y Cultura Pop',
        nameFRFR: 'Célébrités et Culture Pop',
        nameRURU: 'Знаменитости и Поп-культура',
        nameJAJP: '有名人とポップカルチャー',
        nameDEDE: 'Promis & Popkultur',
        namePTBR: 'Celebridades e Cultura Pop',
        nameKOKR: '연예인 및 대중문화',
    },
    {
        name: 'standup_comedy',
        emoji: '🎤',
        index: 8,
        classificationName: 'entertainment_leisure',
        nameZHCN: '脱口秀',
        nameZHTW: '脫口秀',
        nameENUS: 'Stand-up Comedy',
        nameESES: 'Comedia en Vivo',
        nameFRFR: 'Stand-up',
        nameRURU: 'Стендап-комедия',
        nameJAJP: 'スタンドアップコメディ',
        nameDEDE: 'Stand-up-Comedy',
        namePTBR: 'Comédia Stand-up',
        nameKOKR: '스탠드업 코미디',
    },
    {
        name: 'podcasts_audiobooks',
        emoji: '🎧',
        index: 9,
        classificationName: 'entertainment_leisure',
        nameZHCN: '播客与有声书',
        nameZHTW: '播客與有聲書',
        nameENUS: 'Podcasts & Audiobooks',
        nameESES: 'Podcasts y Audiolibros',
        nameFRFR: 'Podcasts et Livres Audio',
        nameRURU: 'Подкасты и Аудиокниги',
        nameJAJP: 'ポッドキャストとオーディオブック',
        nameDEDE: 'Podcasts & Hörbücher',
        namePTBR: 'Podcasts e Audiolivros',
        nameKOKR: '팟캐스트 및 오디오북',
    },

    // ===================================
    // 生活方式 (Lifestyle)
    // ===================================
    {
        name: 'travel_sharing',
        emoji: '✈️',
        index: 0,
        classificationName: 'lifestyle',
        nameZHCN: '旅游分享',
        nameZHTW: '旅遊分享',
        nameENUS: 'Travel Sharing',
        nameESES: 'Compartir Viajes',
        nameFRFR: 'Partage de Voyage',
        nameRURU: 'Путешествия',
        nameJAJP: '旅行シェア',
        nameDEDE: 'Reise-Sharing',
        namePTBR: 'Compartilhamento de Viagem',
        nameKOKR: '여행 공유',
    },
    {
        name: 'food_paradise',
        emoji: '🍳',
        index: 1,
        classificationName: 'lifestyle',
        nameZHCN: '美食天地',
        nameZHTW: '美食天地',
        nameENUS: 'Food Paradise',
        nameESES: 'Paraíso Gastronómico',
        nameFRFR: 'Paradis Culinaire',
        nameRURU: 'Кулинарный Рай',
        nameJAJP: 'グルメパラダイス',
        nameDEDE: 'Kulinarisches Paradies',
        namePTBR: 'Paraíso Gastronômico',
        nameKOKR: '음식 천국',
    },
    {
        name: 'home_decoration',
        emoji: '🏡',
        index: 2,
        classificationName: 'lifestyle',
        nameZHCN: '家居与装修',
        nameZHTW: '家居與裝修',
        nameENUS: 'Home & Decoration',
        nameESES: 'Hogar y Decoración',
        nameFRFR: 'Maison et Décoration',
        nameRURU: 'Дом и Декор',
        nameJAJP: 'ホームと装飾',
        nameDEDE: 'Zuhause & Dekoration',
        namePTBR: 'Casa e Decoração',
        nameKOKR: '홈 및 인테리어',
    },
    {
        name: 'pet_world',
        emoji: '🐶',
        index: 3,
        classificationName: 'lifestyle',
        nameZHCN: '宠物天地',
        nameZHTW: '寵物天地',
        nameENUS: 'Pet World',
        nameESES: 'Mundo de Mascotas',
        nameFRFR: 'Monde des Animaux',
        nameRURU: 'Мир Домашних Животных',
        nameJAJP: 'ペットの世界',
        nameDEDE: 'Haustier-Welt',
        namePTBR: 'Mundo dos Pets',
        nameKOKR: '반려동물 세계',
    },
    {
        name: 'fashion_beauty',
        emoji: '💄',
        index: 4,
        classificationName: 'lifestyle',
        nameZHCN: '穿搭与美妆',
        nameZHTW: '穿搭與美妝',
        nameENUS: 'Fashion & Beauty',
        nameESES: 'Moda y Belleza',
        nameFRFR: 'Mode et Beauté',
        nameRURU: 'Мода и Красота',
        nameJAJP: 'ファッションと美容',
        nameDEDE: 'Mode & Schönheit',
        namePTBR: 'Moda e Beleza',
        nameKOKR: '패션 및 뷰티',
    },
    {
        name: 'cars_driving',
        emoji: '🚗',
        index: 5,
        classificationName: 'lifestyle',
        nameZHCN: '汽车与驾驶',
        nameZHTW: '汽車與駕駛',
        nameENUS: 'Cars & Driving',
        nameESES: 'Coches y Conducción',
        nameFRFR: 'Voitures et Conduite',
        nameRURU: 'Автомобили и Вождение',
        nameJAJP: '自動車と運転',
        nameDEDE: 'Autos & Fahren',
        namePTBR: 'Carros e Direção',
        nameKOKR: '자동차 및 운전',
    },
    {
        name: 'parenting_family',
        emoji: '👨‍👩‍👧‍👦',
        index: 6,
        classificationName: 'lifestyle',
        nameZHCN: '育儿与家庭',
        nameZHTW: '育兒與家庭',
        nameENUS: 'Parenting & Family',
        nameESES: 'Crianza y Familia',
        nameFRFR: 'Parentalité et Famille',
        nameRURU: 'Воспитание и Семья',
        nameJAJP: '子育てと家族',
        nameDEDE: 'Elternschaft & Familie',
        namePTBR: 'Paternidade e Família',
        nameKOKR: '육아 및 가족',
    },
    {
        name: 'emotional_life',
        emoji: '❤️‍🔥',
        index: 7,
        classificationName: 'lifestyle',
        nameZHCN: '情感生活',
        nameZHTW: '情感生活',
        nameENUS: 'Emotional Life',
        nameESES: 'Vida Emocional',
        nameFRFR: 'Vie Émotionnelle',
        nameRURU: 'Эмоциональная Жизнь',
        nameJAJP: '感情生活',
        nameDEDE: 'Gefühlsleben',
        namePTBR: 'Vida Emocional',
        nameKOKR: '감정 생활',
    },
    {
        name: 'minimalism_simple_living',
        emoji: '🧘',
        index: 8,
        classificationName: 'lifestyle',
        nameZHCN: '极简与慢生活',
        nameZHTW: '極簡與慢生活',
        nameENUS: 'Minimalism & Simple Living',
        nameESES: 'Minimalismo y Vida Sencilla',
        nameFRFR: 'Minimalisme et Vie Simple',
        nameRURU: 'Минимализм и Простая Жизнь',
        nameJAJP: 'ミニマリズムとシンプルライフ',
        nameDEDE: 'Minimalismus & Einfaches Leben',
        namePTBR: 'Minimalismo e Vida Simples',
        nameKOKR: '미니멀리즘과 단순한 삶',
    },

    // ===================================
    // 职业发展 (Career Development)
    // ===================================
    {
        name: 'job_workplace',
        emoji: '🧑‍💼',
        index: 0,
        classificationName: 'career_development',
        nameZHCN: '求职与职场',
        nameZHTW: '求職與職場',
        nameENUS: 'Job Search & Workplace',
        nameESES: 'Búsqueda de Empleo y Lugar de Trabajo',
        nameFRFR: "Recherche d'Emploi et Lieu de Travail",
        nameRURU: 'Поиск Работы и Рабочее Место',
        nameJAJP: '就職活動と職場',
        nameDEDE: 'Jobsuche & Arbeitsplatz',
        namePTBR: 'Busca de Emprego e Local de Trabalho',
        nameKOKR: '구직 및 직장',
    },
    {
        name: 'finance_investment',
        emoji: '💸',
        index: 1,
        classificationName: 'career_development',
        nameZHCN: '理财投资',
        nameZHTW: '理財投資',
        nameENUS: 'Finance & Investment',
        nameESES: 'Finanzas e Inversión',
        nameFRFR: 'Finance et Investissement',
        nameRURU: 'Финансы и Инвестиции',
        nameJAJP: '金融と投資',
        nameDEDE: 'Finanzen & Investment',
        namePTBR: 'Finanças e Investimento',
        nameKOKR: '금융 및 투자',
    },
    {
        name: 'study_abroad_immigration',
        emoji: '🧳',
        index: 2,
        classificationName: 'career_development',
        nameZHCN: '留学与移民',
        nameZHTW: '留學與移民',
        nameENUS: 'Study Abroad & Immigration',
        nameESES: 'Estudiar en el Extranjero e Inmigración',
        nameFRFR: "Études à l'Étranger et Immigration",
        nameRURU: 'Обучение за Рубежом и Иммиграция',
        nameJAJP: '留学と移民',
        nameDEDE: 'Auslandsstudium & Immigration',
        namePTBR: 'Estudar no Exterior e Imigração',
        nameKOKR: '유학 및 이민',
    },
    {
        name: 'entrepreneurship_exchange',
        emoji: '📈',
        index: 3,
        classificationName: 'career_development',
        nameZHCN: '创业交流',
        nameZHTW: '創業交流',
        nameENUS: 'Entrepreneurship Exchange',
        nameESES: 'Intercambio de Emprendimiento',
        nameFRFR: "Échange d'Entrepreneuriat",
        nameRURU: 'Предпринимательский Обмен',
        nameJAJP: '起業交流',
        nameDEDE: 'Unternehmertum-Austausch',
        namePTBR: 'Intercâmbio de Empreendedorismo',
        nameKOKR: '창업 교류',
    },
    {
        name: 'industry_talk',
        emoji: '🏭',
        index: 4,
        classificationName: 'career_development',
        nameZHCN: '行业交流',
        nameZHTW: '行業交流',
        nameENUS: 'Industry Talk',
        nameESES: 'Charla Sectorial',
        nameFRFR: 'Discussion Sectorielle',
        nameRURU: 'Отраслевые Обсуждения',
        nameJAJP: '業界トーク',
        nameDEDE: 'Branchentalk',
        namePTBR: 'Discussão Setorial',
        nameKOKR: '업계 토크',
    },
    {
        name: 'productivity_hacks',
        emoji: '⏱️',
        index: 5,
        classificationName: 'career_development',
        nameZHCN: '效率与工具',
        nameZHTW: '效率與工具',
        nameENUS: 'Productivity & Tools',
        nameESES: 'Productividad y Herramientas',
        nameFRFR: 'Productivité et Outils',
        nameRURU: 'Продуктивность и Инструменты',
        nameJAJP: '生産性とツール',
        nameDEDE: 'Produktivität & Tools',
        namePTBR: 'Produtividade e Ferramentas',
        nameKOKR: '생산성 및 도구',
    },
    {
        name: 'side_hustles_freelance',
        emoji: '💡',
        index: 6,
        classificationName: 'career_development',
        nameZHCN: '副业与自由职业',
        nameZHTW: '副業與自由職業',
        nameENUS: 'Side Hustles & Freelancing',
        nameESES: 'Pluriempleo y Freelance',
        nameFRFR: 'Activités Secondaires et Freelance',
        nameRURU: 'Подработки и Фриланс',
        nameJAJP: '副業とフリーランス',
        nameDEDE: 'Nebenverdienst & Freiberuflichkeit',
        namePTBR: 'Renda Extra e Freelancing',
        nameKOKR: '부업 및 프리랜서',
    },
    {
        name: 'management_leadership',
        emoji: '👑',
        index: 7,
        classificationName: 'career_development',
        nameZHCN: '管理与领导力',
        nameZHTW: '管理與領導力',
        nameENUS: 'Management & Leadership',
        nameESES: 'Gestión y Liderazgo',
        nameFRFR: 'Management et Leadership',
        nameRURU: 'Менеджмент и Лидерство',
        nameJAJP: 'マネジメントとリーダーシップ',
        nameDEDE: 'Management & Führung',
        namePTBR: 'Gestão e Liderança',
        nameKOKR: '경영 및 리더십',
    },

    // ===================================
    // 人文艺术 (Arts & Humanities)
    // ===================================
    {
        name: 'literature_poetry',
        emoji: '📜',
        index: 0,
        classificationName: 'arts_humanities',
        nameZHCN: '文学与诗歌',
        nameZHTW: '文學與詩歌',
        nameENUS: 'Literature & Poetry',
        nameESES: 'Literatura y Poesía',
        nameFRFR: 'Littérature et Poésie',
        nameRURU: 'Литература и Поэзия',
        nameJAJP: '文学と詩',
        nameDEDE: 'Literatur & Poesie',
        namePTBR: 'Literatura e Poesia',
        nameKOKR: '문학 및 시',
    },
    {
        name: 'visual_arts',
        emoji: '🖼️',
        index: 1,
        classificationName: 'arts_humanities',
        nameZHCN: '视觉艺术',
        nameZHTW: '視覺藝術',
        nameENUS: 'Visual Arts',
        nameESES: 'Artes Visuales',
        nameFRFR: 'Arts Visuels',
        nameRURU: 'Визуальные Искусства',
        nameJAJP: 'ビジュアルアート',
        nameDEDE: 'Bildende Kunst',
        namePTBR: 'Artes Visuais',
        nameKOKR: '시각 예술',
    },
    {
        name: 'performing_arts',
        emoji: '🎭',
        index: 2,
        classificationName: 'arts_humanities',
        nameZHCN: '表演艺术',
        nameZHTW: '表演藝術',
        nameENUS: 'Performing Arts',
        nameESES: 'Artes Escénicas',
        nameFRFR: 'Arts de la Scène',
        nameRURU: 'Исполнительские Искусства',
        nameJAJP: '舞台芸術',
        nameDEDE: 'Darstellende Kunst',
        namePTBR: 'Artes Cênicas',
        nameKOKR: '공연 예술',
    },
    {
        name: 'music_theory_composition',
        emoji: '🎼',
        index: 3,
        classificationName: 'arts_humanities',
        nameZHCN: '乐理与作曲',
        nameZHTW: '樂理與作曲',
        nameENUS: 'Music Theory & Composition',
        nameESES: 'Teoría Musical y Composición',
        nameFRFR: 'Théorie Musicale et Composition',
        nameRURU: 'Теория Музыки и Композиция',
        nameJAJP: '音楽理論と作曲',
        nameDEDE: 'Musiktheorie & Komposition',
        namePTBR: 'Teoria Musical e Composição',
        nameKOKR: '음악 이론 및 작곡',
    },
    {
        name: 'mythology_folklore',
        emoji: '🦄',
        index: 4,
        classificationName: 'arts_humanities',
        nameZHCN: '神话与民俗',
        nameZHTW: '神話與民俗',
        nameENUS: 'Mythology & Folklore',
        nameESES: 'Mitología y Folclore',
        nameFRFR: 'Mythologie et Folklore',
        nameRURU: 'Мифология и Фольклор',
        nameJAJP: '神話と民間伝承',
        nameDEDE: 'Mythologie & Folklore',
        namePTBR: 'Mitologia e Folclore',
        nameKOKR: '신화 및 민속',
    },
    {
        name: 'architecture',
        emoji: '🏗️',
        index: 5,
        classificationName: 'arts_humanities',
        nameZHCN: '建筑艺术',
        nameZHTW: '建築藝術',
        nameENUS: 'Architecture',
        nameESES: 'Arquitectura',
        nameFRFR: 'Architecture',
        nameRURU: 'Архитектура',
        nameJAJP: '建築',
        nameDEDE: 'Architektur',
        namePTBR: 'Arquitetura',
        nameKOKR: '건축',
    },

    // ===================================
    // 科学与自然 (Science & Nature)
    // ===================================
    {
        name: 'physics_astronomy',
        emoji: '🌌',
        index: 0,
        classificationName: 'science_nature',
        nameZHCN: '物理与天文',
        nameZHTW: '物理與天文',
        nameENUS: 'Physics & Astronomy',
        nameESES: 'Física y Astronomía',
        nameFRFR: 'Physique et Astronomie',
        nameRURU: 'Физика и Астрономия',
        nameJAJP: '物理学と天文学',
        nameDEDE: 'Physik & Astronomie',
        namePTBR: 'Física e Astronomia',
        nameKOKR: '물리학 및 천문학',
    },
    {
        name: 'biology_genetics',
        emoji: '🧬',
        index: 1,
        classificationName: 'science_nature',
        nameZHCN: '生物与遗传',
        nameZHTW: '生物與遺傳',
        nameENUS: 'Biology & Genetics',
        nameESES: 'Biología y Genética',
        nameFRFR: 'Biologie et Génétique',
        nameRURU: 'Биология и Генетика',
        nameJAJP: '生物学と遺伝学',
        nameDEDE: 'Biologie & Genetik',
        namePTBR: 'Biologia e Genética',
        nameKOKR: '생물학 및 유전학',
    },
    {
        name: 'chemistry_materials',
        emoji: '🧪',
        index: 2,
        classificationName: 'science_nature',
        nameZHCN: '化学与材料',
        nameZHTW: '化學與材料',
        nameENUS: 'Chemistry & Materials',
        nameESES: 'Química y Materiales',
        nameFRFR: 'Chimie et Matériaux',
        nameRURU: 'Химия и Материалы',
        nameJAJP: '化学と材料',
        nameDEDE: 'Chemie & Materialien',
        namePTBR: 'Química e Materiais',
        nameKOKR: '화학 및 재료',
    },
    {
        name: 'earth_sciences_geology',
        emoji: '🌋',
        index: 3,
        classificationName: 'science_nature',
        nameZHCN: '地球科学与地质',
        nameZHTW: '地球科學與地質',
        nameENUS: 'Earth Sciences & Geology',
        nameESES: 'Ciencias de la Tierra y Geología',
        nameFRFR: 'Sciences de la Terre et Géologie',
        nameRURU: 'Науки о Земле и Геология',
        nameJAJP: '地球科学と地質学',
        nameDEDE: 'Geowissenschaften & Geologie',
        namePTBR: 'Ciências da Terra e Geologia',
        nameKOKR: '지구 과학 및 지질학',
    },
    {
        name: 'environmental_conservation',
        emoji: '♻️',
        index: 4,
        classificationName: 'science_nature',
        nameZHCN: '环境与保护',
        nameZHTW: '環境與保護',
        nameENUS: 'Environmental Conservation',
        nameESES: 'Conservación Ambiental',
        nameFRFR: "Conservation de l'Environnement",
        nameRURU: 'Охрана Окружающей Среды',
        nameJAJP: '環境保全',
        nameDEDE: 'Umweltschutz',
        namePTBR: 'Conservação Ambiental',
        nameKOKR: '환경 보전',
    },
    {
        name: 'space_exploration',
        emoji: '🚀',
        index: 5,
        classificationName: 'science_nature',
        nameZHCN: '太空探索',
        nameZHTW: '太空探索',
        nameENUS: 'Space Exploration',
        nameESES: 'Exploración Espacial',
        nameFRFR: 'Exploration Spatiale',
        nameRURU: 'Исследование Космоса',
        nameJAJP: '宇宙探査',
        nameDEDE: 'Weltraumforschung',
        namePTBR: 'Exploração Espacial',
        nameKOKR: '우주 탐사',
    },
    {
        name: 'mathematics',
        emoji: '🧮',
        index: 6,
        classificationName: 'science_nature',
        nameZHCN: '数学',
        nameZHTW: '數學',
        nameENUS: 'Mathematics',
        nameESES: 'Matemáticas',
        nameFRFR: 'Mathématiques',
        nameRURU: 'Математика',
        nameJAJP: '数学',
        nameDEDE: 'Mathematik',
        namePTBR: 'Matemática',
        nameKOKR: '수학',
    },

    // ===================================
    // 健康与保健 (Health & Wellness)
    // ===================================
    {
        name: 'fitness_health',
        emoji: '🏃',
        index: 0,
        classificationName: 'health_wellness',
        nameZHCN: '健身与健康',
        nameZHTW: '健身與健康',
        nameENUS: 'Fitness & Health',
        nameESES: 'Fitness y Salud',
        nameFRFR: 'Fitness et Santé',
        nameRURU: 'Фитнес и Здоровье',
        nameJAJP: 'フィットネスと健康',
        nameDEDE: 'Fitness & Gesundheit',
        namePTBR: 'Fitness e Saúde',
        nameKOKR: '피트니스 및 건강',
    },
    {
        name: 'nutrition_diet',
        emoji: '🥗',
        index: 1,
        classificationName: 'health_wellness',
        nameZHCN: '营养与饮食',
        nameZHTW: '營養與飲食',
        nameENUS: 'Nutrition & Diet',
        nameESES: 'Nutrición y Dieta',
        nameFRFR: 'Nutrition et Régime',
        nameRURU: 'Питание и Диета',
        nameJAJP: '栄養と食事',
        nameDEDE: 'Ernährung & Diät',
        namePTBR: 'Nutrição e Dieta',
        nameKOKR: '영양 및 식단',
    },
    {
        name: 'mental_health',
        emoji: '🧠',
        index: 2,
        classificationName: 'health_wellness',
        nameZHCN: '心理健康',
        nameZHTW: '心理健康',
        nameENUS: 'Mental Health',
        nameESES: 'Salud Mental',
        nameFRFR: 'Santé Mentale',
        nameRURU: 'Психическое Здоровье',
        nameJAJP: 'メンタルヘルス',
        nameDEDE: 'Psychische Gesundheit',
        namePTBR: 'Saúde Mental',
        nameKOKR: '정신 건강',
    },
    {
        name: 'mindfulness_meditation',
        emoji: '🧘‍♀️',
        index: 3,
        classificationName: 'health_wellness',
        nameZHCN: '正念与冥想',
        nameZHTW: '正念與冥想',
        nameENUS: 'Mindfulness & Meditation',
        nameESES: 'Mindfulness y Meditación',
        nameFRFR: 'Pleine Conscience et Méditation',
        nameRURU: 'Осознанность и Медитация',
        nameJAJP: 'マインドフルネスと瞑想',
        nameDEDE: 'Achtsamkeit & Meditation',
        namePTBR: 'Mindfulness e Meditação',
        nameKOKR: '마음챙김 및 명상',
    },
    {
        name: 'alternative_medicine',
        emoji: '🌿',
        index: 4,
        classificationName: 'health_wellness',
        nameZHCN: '替代医学',
        nameZHTW: '替代醫學',
        nameENUS: 'Alternative Medicine',
        nameESES: 'Medicina Alternativa',
        nameFRFR: 'Médecine Alternative',
        nameRURU: 'Альтернативная Медицина',
        nameJAJP: '代替医療',
        nameDEDE: 'Alternative Medizin',
        namePTBR: 'Medicina Alternativa',
        nameKOKR: '대체 의학',
    },
    {
        name: 'biohacking_longevity',
        emoji: '⏳',
        index: 5,
        classificationName: 'health_wellness',
        nameZHCN: '生物骇客与长寿',
        nameZHTW: '生物駭客與長壽',
        nameENUS: 'Biohacking & Longevity',
        nameESES: 'Biohacking y Longevidad',
        nameFRFR: 'Biohacking et Longévité',
        nameRURU: 'Биохакинг и Долголетие',
        nameJAJP: 'バイオハッキングと長寿',
        nameDEDE: 'Biohacking & Langlebigkeit',
        namePTBR: 'Biohacking e Longevidade',
        nameKOKR: '바이오해킹 및 장수',
    },

    // ===================================
    // 体育与运动 (Sports & Recreation)
    // ===================================
    {
        name: 'soccer_football',
        emoji: '⚽',
        index: 0,
        classificationName: 'sports_recreation',
        nameZHCN: '足球',
        nameZHTW: '足球',
        nameENUS: 'Soccer / Football',
        nameESES: 'Fútbol',
        nameFRFR: 'Football',
        nameRURU: 'Футбол',
        nameJAJP: 'サッカー',
        nameDEDE: 'Fußball',
        namePTBR: 'Futebol',
        nameKOKR: '축구',
    },
    {
        name: 'basketball',
        emoji: '🏀',
        index: 1,
        classificationName: 'sports_recreation',
        nameZHCN: '篮球',
        nameZHTW: '籃球',
        nameENUS: 'Basketball',
        nameESES: 'Baloncesto',
        nameFRFR: 'Basketball',
        nameRURU: 'Баскетбол',
        nameJAJP: 'バスケットボール',
        nameDEDE: 'Basketball',
        namePTBR: 'Basquete',
        nameKOKR: '농구',
    },
    {
        name: 'american_football',
        emoji: '🏈',
        index: 2,
        classificationName: 'sports_recreation',
        nameZHCN: '美式橄榄球',
        nameZHTW: '美式橄欖球',
        nameENUS: 'American Football',
        nameESES: 'Fútbol Americano',
        nameFRFR: 'Football Américain',
        nameRURU: 'Американский Футбол',
        nameJAJP: 'アメリカンフットボール',
        nameDEDE: 'American Football',
        namePTBR: 'Futebol Americano',
        nameKOKR: '미식 축구',
    },
    {
        name: 'motorsports',
        emoji: '🏎️',
        index: 3,
        classificationName: 'sports_recreation',
        nameZHCN: '赛车运动',
        nameZHTW: '賽車運動',
        nameENUS: 'Motorsports',
        nameESES: 'Deportes de Motor',
        nameFRFR: 'Sports Mécaniques',
        nameRURU: 'Автоспорт',
        nameJAJP: 'モータースポーツ',
        nameDEDE: 'Motorsport',
        namePTBR: 'Esportes a Motor',
        nameKOKR: '모터스포츠',
    },
    {
        name: 'esports_competitive_gaming',
        emoji: '🏆',
        index: 4,
        classificationName: 'sports_recreation',
        nameZHCN: '电子竞技',
        nameZHTW: '電子競技',
        nameENUS: 'eSports & Competitive Gaming',
        nameESES: 'eSports y Juego Competitivo',
        nameFRFR: 'eSports et Jeu Compétitif',
        nameRURU: 'Киберспорт и Соревновательные Игры',
        nameJAJP: 'eスポーツと競技ゲーミング',
        nameDEDE: 'eSports & Kompetitives Gaming',
        namePTBR: 'eSports e Jogos Competitivos',
        nameKOKR: 'e스포츠 및 경쟁 게임',
    },
    {
        name: 'outdoor_adventures',
        emoji: '🏕️',
        index: 5,
        classificationName: 'sports_recreation',
        nameZHCN: '户外探险',
        nameZHTW: '戶外探險',
        nameENUS: 'Outdoor Adventures',
        nameESES: 'Aventuras al Aire Libre',
        nameFRFR: 'Aventures en Plein Air',
        nameRURU: 'Приключения на Открытом Воздухе',
        nameJAJP: 'アウトドアアドベンチャー',
        nameDEDE: 'Outdoor-Abenteuer',
        namePTBR: 'Aventuras ao Ar Livre',
        nameKOKR: '야외 모험',
    },
    {
        name: 'martial_arts',
        emoji: '🥋',
        index: 6,
        classificationName: 'sports_recreation',
        nameZHCN: '武术格斗',
        nameZHTW: '武術格鬥',
        nameENUS: 'Martial Arts',
        nameESES: 'Artes Marciales',
        nameFRFR: 'Arts Martiaux',
        nameRURU: 'Боевые Искусства',
        nameJAJP: '武道',
        nameDEDE: 'Kampfsport',
        namePTBR: 'Artes Marciais',
        nameKOKR: '무술',
    },
    {
        name: 'tennis_racket_sports',
        emoji: '🎾',
        index: 7,
        classificationName: 'sports_recreation',
        nameZHCN: '网球与球拍运动',
        nameZHTW: '網球與球拍運動',
        nameENUS: 'Tennis & Racket Sports',
        nameESES: 'Tenis y Deportes de Raqueta',
        nameFRFR: 'Tennis et Sports de Raquette',
        nameRURU: 'Теннис и Ракетные Виды Спорта',
        nameJAJP: 'テニスとラケットスポーツ',
        nameDEDE: 'Tennis & Schlägersport',
        namePTBR: 'Tênis e Esportes de Raquete',
        nameKOKR: '테니스 및 라켓 스포츠',
    },

    // ===================================
    // 爱好与手工艺 (Hobbies & Crafts)
    // ===================================
    {
        name: 'gardening_plants',
        emoji: '🌱',
        index: 0,
        classificationName: 'hobbies_crafts',
        nameZHCN: '园艺与植物',
        nameZHTW: '園藝與植物',
        nameENUS: 'Gardening & Plants',
        nameESES: 'Jardinería y Plantas',
        nameFRFR: 'Jardinage et Plantes',
        nameRURU: 'Садоводство и Растения',
        nameJAJP: 'ガーデニングと植物',
        nameDEDE: 'Gartenarbeit & Pflanzen',
        namePTBR: 'Jardinagem e Plantas',
        nameKOKR: '원예 및 식물',
    },
    {
        name: 'diy_makers',
        emoji: '🧩',
        index: 1,
        classificationName: 'hobbies_crafts',
        nameZHCN: 'DIY 与创客',
        nameZHTW: 'DIY 與創客',
        nameENUS: 'DIY & Makers',
        nameESES: 'DIY y Creadores',
        nameFRFR: 'DIY et Créateurs',
        nameRURU: 'DIY и Создатели',
        nameJAJP: 'DIYとメーカー',
        nameDEDE: 'DIY & Maker',
        namePTBR: 'DIY e Criadores',
        nameKOKR: 'DIY 및 메이커',
    },
    {
        name: 'collecting',
        emoji: '🪙',
        index: 2,
        classificationName: 'hobbies_crafts',
        nameZHCN: '收藏',
        nameZHTW: '收藏',
        nameENUS: 'Collecting',
        nameESES: 'Coleccionismo',
        nameFRFR: 'Collection',
        nameRURU: 'Коллекционирование',
        nameJAJP: '収集',
        nameDEDE: 'Sammeln',
        namePTBR: 'Colecionismo',
        nameKOKR: '수집',
    },
    {
        name: 'woodworking_metalworking',
        emoji: '🪵',
        index: 3,
        classificationName: 'hobbies_crafts',
        nameZHCN: '木工与金工',
        nameZHTW: '木工與金工',
        nameENUS: 'Woodworking & Metalworking',
        nameESES: 'Carpintería y Metalurgia',
        nameFRFR: 'Travail du Bois et du Métal',
        nameRURU: 'Деревообработка и Металлообработка',
        nameJAJP: '木工と金工',
        nameDEDE: 'Holz- & Metallbearbeitung',
        namePTBR: 'Marcenaria e Metalurgia',
        nameKOKR: '목공 및 금속 공예',
    },
    {
        name: 'knitting_sewing_textiles',
        emoji: '🧶',
        index: 4,
        classificationName: 'hobbies_crafts',
        nameZHCN: '编织缝纫与纺织',
        nameZHTW: '編織縫紉與紡織',
        nameENUS: 'Knitting, Sewing & Textiles',
        nameESES: 'Tejido, Costura y Textiles',
        nameFRFR: 'Tricot, Couture et Textiles',
        nameRURU: 'Вязание, Шитье и Текстиль',
        nameJAJP: '編み物、裁縫、テキスタイル',
        nameDEDE: 'Stricken, Nähen & Textilien',
        namePTBR: 'Tricô, Costura e Têxteis',
        nameKOKR: '뜨개질, 바느질 및 직물',
    },
    {
        name: 'model_making',
        emoji: '✈️',
        index: 5,
        classificationName: 'hobbies_crafts',
        nameZHCN: '模型制作',
        nameZHTW: '模型製作',
        nameENUS: 'Model Making',
        nameESES: 'Modelismo',
        nameFRFR: 'Modélisme',
        nameRURU: 'Моделизм',
        nameJAJP: '模型製作',
        nameDEDE: 'Modellbau',
        namePTBR: 'Modelismo',
        nameKOKR: '모형 제작',
    },
    {
        name: 'home_brewing_distilling',
        emoji: '⚗️',
        index: 6,
        classificationName: 'hobbies_crafts',
        nameZHCN: '家庭酿造',
        nameZHTW: '家庭釀造',
        nameENUS: 'Homebrewing & Distilling',
        nameESES: 'Elaboración Casera y Destilación',
        nameFRFR: 'Brassage et Distillation Maison',
        nameRURU: 'Домашнее Пивоварение и Дистилляция',
        nameJAJP: '自家醸造と蒸留',
        nameDEDE: 'Heimbrauen & Destillieren',
        namePTBR: 'Cerveja Artesanal e Destilação',
        nameKOKR: '자가 양조 및 증류',
    },
    {
        name: 'calligraphy_penmanship',
        emoji: '✒️',
        index: 7,
        classificationName: 'hobbies_crafts',
        nameZHCN: '书法与手写',
        nameZHTW: '書法與手寫',
        nameENUS: 'Calligraphy & Penmanship',
        nameESES: 'Caligrafía y Escritura',
        nameFRFR: 'Calligraphie et Écriture',
        nameRURU: 'Каллиграфия и Чистописание',
        nameJAJP: '書道とペン習字',
        nameDEDE: 'Kalligraphie & Handschrift',
        namePTBR: 'Caligrafia e Escrita',
        nameKOKR: '서예 및 필기',
    },

    // ===================================
    // 社会与文化 (Society & Culture)
    // ===================================
    {
        name: 'local_life',
        emoji: '📍',
        index: 0,
        classificationName: 'society_culture',
        nameZHCN: '同城生活',
        nameZHTW: '同城生活',
        nameENUS: 'Local Life',
        nameESES: 'Vida Local',
        nameFRFR: 'Vie Locale',
        nameRURU: 'Местная Жизнь',
        nameJAJP: '地域生活',
        nameDEDE: 'Lokales Leben',
        namePTBR: 'Vida Local',
        nameKOKR: '지역 생활',
    },
    {
        name: 'politics',
        emoji: '🏛️',
        index: 1,
        classificationName: 'society_culture',
        nameZHCN: '政治',
        nameZHTW: '政治',
        nameENUS: 'Politics',
        nameESES: 'Política',
        nameFRFR: 'Politique',
        nameRURU: 'Политика',
        nameJAJP: '政治',
        nameDEDE: 'Politik',
        namePTBR: 'Política',
        nameKOKR: '정치',
    },
    {
        name: 'news_journalism',
        emoji: '🗞️',
        index: 2,
        classificationName: 'society_culture',
        nameZHCN: '新闻与新闻业',
        nameZHTW: '新聞與新聞業',
        nameENUS: 'News & Journalism',
        nameESES: 'Noticias y Periodismo',
        nameFRFR: 'Actualités et Journalisme',
        nameRURU: 'Новости и Журналистика',
        nameJAJP: 'ニュースとジャーナリズム',
        nameDEDE: 'Nachrichten & Journalismus',
        namePTBR: 'Notícias e Jornalismo',
        nameKOKR: '뉴스 및 저널리즘',
    },
    {
        name: 'social_issues',
        emoji: '🫂',
        index: 3,
        classificationName: 'society_culture',
        nameZHCN: '社会议题',
        nameZHTW: '社會議題',
        nameENUS: 'Social Issues',
        nameESES: 'Asuntos Sociales',
        nameFRFR: 'Questions Sociales',
        nameRURU: 'Социальные Вопросы',
        nameJAJP: '社会問題',
        nameDEDE: 'Soziale Themen',
        namePTBR: 'Questões Sociais',
        nameKOKR: '사회 문제',
    },
    {
        name: 'sustainability',
        emoji: '🌱',
        index: 4,
        classificationName: 'society_culture',
        nameZHCN: '可持续发展',
        nameZHTW: '可持續發展',
        nameENUS: 'Sustainability',
        nameESES: 'Sostenibilidad',
        nameFRFR: 'Durabilité',
        nameRURU: 'Устойчивое Развитие',
        nameJAJP: '持続可能性',
        nameDEDE: 'Nachhaltigkeit',
        namePTBR: 'Sustentabilidade',
        nameKOKR: '지속 가능성',
    },
    {
        name: 'cultural_studies_anthropology',
        emoji: '🗺️',
        index: 5,
        classificationName: 'society_culture',
        nameZHCN: '文化研究与人类学',
        nameZHTW: '文化研究與人類學',
        nameENUS: 'Cultural Studies & Anthropology',
        nameESES: 'Estudios Culturales y Antropología',
        nameFRFR: 'Études Culturelles et Anthropologie',
        nameRURU: 'Культурные Исследования и Антропология',
        nameJAJP: '文化研究と人類学',
        nameDEDE: 'Kulturwissenschaft & Anthropologie',
        namePTBR: 'Estudos Culturais e Antropologia',
        nameKOKR: '문화 연구 및 인류학',
    },
];

async function main() {
    console.log('开始创建分类数据...');

    for (const classification of classifications) {
        await prisma.classification.upsert({
            where: { name: classification.name },
            update: {},
            create: classification,
        });
        console.log(`创建或确认分类: ${classification.nameZHCN}`);
    }

    console.log('开始创建主题数据...');

    for (const topic of topics) {
        await prisma.topic.upsert({
            where: { name: topic.name },
            update: {},
            create: topic,
        });
        console.log(`创建或确认主题: ${topic.nameZHCN}`);
    }

    console.log('数据创建完成！');
}

main()
    .catch((e) => {
        console.error(e);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
