import { PrismaClient } from "../src/generated/prisma/client.js";

const prisma = new PrismaClient();

// ...existing code...
const classifications = [
  {
    name: 'general',
    emoji: '🌐',
    index: 0,
    nameZHCN: '综合类',
    nameZHTW: '綜合類',
    nameENUS: 'General',
    nameESES: 'General',
    nameFRFR: 'Général',
    nameRURU: 'Общий',
    nameJAJP: '総合',
    nameDEDE: 'Allgemein',
    namePTBR: 'Geral',
    nameKOKR: '종합',
  },
  {
    name: 'learning_education',
    emoji: '📚',
    index: 1,
    nameZHCN: '学习与教育',
    nameZHTW: '學習與教育',
    nameENUS: 'Learning & Education',
    nameESES: 'Aprendizaje y Educación',
    nameFRFR: 'Apprentissage et Éducation',
    nameRURU: 'Обучение и Образование',
    nameJAJP: '学習と教育',
    nameDEDE: 'Lernen & Bildung',
    namePTBR: 'Aprendizado e Educação',
    nameKOKR: '학습 및 교육',
  },
  {
    name: 'entertainment_leisure',
    emoji: '🎮',
    index: 2,
    nameZHCN: '娱乐休闲',
    nameZHTW: '娛樂休閒',
    nameENUS: 'Entertainment & Leisure',
    nameESES: 'Entretenimiento y Ocio',
    nameFRFR: 'Divertissement et Loisirs',
    nameRURU: 'Развлечения и Досуг',
    nameJAJP: 'エンターテイメントとレジャー',
    nameDEDE: 'Unterhaltung & Freizeit',
    namePTBR: 'Entretenimento e Lazer',
    nameKOKR: '엔터테인먼트 및 레저',
  },
  {
    name: 'lifestyle',
    emoji: '✈️',
    index: 3,
    nameZHCN: '生活方式',
    nameZHTW: '生活方式',
    nameENUS: 'Lifestyle',
    nameESES: 'Estilo de Vida',
    nameFRFR: 'Style de Vie',
    nameRURU: 'Образ Жизни',
    nameJAJP: 'ライフスタイル',
    nameDEDE: 'Lebensstil',
    namePTBR: 'Estilo de Vida',
    nameKOKR: '라이프스타일',
  },
  {
    name: 'career_development',
    emoji: '💼',
    index: 4,
    nameZHCN: '职业发展',
    nameZHTW: '職業發展',
    nameENUS: 'Career Development',
    nameESES: 'Desarrollo Profesional',
    nameFRFR: 'Développement de Carrière',
    nameRURU: 'Карьерное Развитие',
    nameJAJP: 'キャリア開発',
    nameDEDE: 'Karriereentwicklung',
    namePTBR: 'Desenvolvimento Profissional',
    nameKOKR: '경력 개발',
  },
  {
    name: 'technology_creation',
    emoji: '🛠️',
    index: 5,
    nameZHCN: '技术与创作',
    nameZHTW: '技術與創作',
    nameENUS: 'Technology & Creation',
    nameESES: 'Tecnología y Creación',
    nameFRFR: 'Technologie et Création',
    nameRURU: 'Технологии и Творчество',
    nameJAJP: 'テクノロジーと創作',
    nameDEDE: 'Technologie & Kreation',
    namePTBR: 'Tecnologia e Criação',
    nameKOKR: '기술 및 창작',
  },
];
// ...existing code...

const topics = [
  // 综合类主题
  {
    name: 'current_events',
    emoji: '📰',
    index: 0,
    classificationName: 'general',
    nameZHCN: '时事热点',
    nameZHTW: '時事熱點',
    nameENUS: 'Current Events',
    nameESES: 'Actualidad',
    nameFRFR: 'Actualités',
    nameRURU: 'Актуальные События',
    nameJAJP: '時事',
    nameDEDE: 'Aktuelle Ereignisse',
    namePTBR: 'Eventos Atuais',
    nameKOKR: '시사',
  },
  {
    name: 'casual_chat',
    emoji: '💬',
    index: 1,
    classificationName: 'general',
    nameZHCN: '灌水闲聊',
    nameZHTW: '灌水閒聊',
    nameENUS: 'Casual Chat',
    nameESES: 'Charla Casual',
    nameFRFR: 'Discussion Décontractée',
    nameRURU: 'Свободное Общение',
    nameJAJP: '雑談',
    nameDEDE: 'Lockerer Chat',
    namePTBR: 'Bate-papo Casual',
    nameKOKR: '자유 대화',
  },
  {
    name: 'new_member_intro',
    emoji: '🤝',
    index: 2,
    classificationName: 'general',
    nameZHCN: '新人报到',
    nameZHTW: '新人報到',
    nameENUS: 'New Member Introduction',
    nameESES: 'Presentación de Nuevos Miembros',
    nameFRFR: 'Présentation des Nouveaux Membres',
    nameRURU: 'Знакомство Новых Участников',
    nameJAJP: '新人紹介',
    nameDEDE: 'Vorstellung Neuer Mitglieder',
    namePTBR: 'Apresentação de Novos Membros',
    nameKOKR: '신규 회원 소개',
  },

  // 学习与教育主题
  {
    name: 'academic_exchange',
    emoji: '📘',
    index: 0,
    classificationName: 'learning_education',
    nameZHCN: '学术交流',
    nameZHTW: '學術交流',
    nameENUS: 'Academic Exchange',
    nameESES: 'Intercambio Académico',
    nameFRFR: 'Échange Académique',
    nameRURU: 'Академический Обмен',
    nameJAJP: '学術交流',
    nameDEDE: 'Akademischer Austausch',
    namePTBR: 'Intercâmbio Acadêmico',
    nameKOKR: '학술 교류',
  },
  {
    name: 'study_skills',
    emoji: '🧠',
    index: 1,
    classificationName: 'learning_education',
    nameZHCN: '学习技巧',
    nameZHTW: '學習技巧',
    nameENUS: 'Study Skills',
    nameESES: 'Técnicas de Estudio',
    nameFRFR: 'Techniques d\'Étude',
    nameRURU: 'Навыки Обучения',
    nameJAJP: '学習スキル',
    nameDEDE: 'Lerntechniken',
    namePTBR: 'Técnicas de Estudo',
    nameKOKR: '학습 기법',
  },
  {
    name: 'programming_dev',
    emoji: '💻',
    index: 2,
    classificationName: 'learning_education',
    nameZHCN: '编程与开发',
    nameZHTW: '編程與開發',
    nameENUS: 'Programming & Development',
    nameESES: 'Programación y Desarrollo',
    nameFRFR: 'Programmation et Développement',
    nameRURU: 'Программирование и Разработка',
    nameJAJP: 'プログラミングと開発',
    nameDEDE: 'Programmierung & Entwicklung',
    namePTBR: 'Programação e Desenvolvimento',
    nameKOKR: '프로그래밍 및 개발',
  },
  {
    name: 'scientific_discussion',
    emoji: '🧪',
    index: 3,
    classificationName: 'learning_education',
    nameZHCN: '科学探讨',
    nameZHTW: '科學探討',
    nameENUS: 'Scientific Discussion',
    nameESES: 'Discusión Científica',
    nameFRFR: 'Discussion Scientifique',
    nameRURU: 'Научная Дискуссия',
    nameJAJP: '科学的議論',
    nameDEDE: 'Wissenschaftliche Diskussion',
    namePTBR: 'Discussão Científica',
    nameKOKR: '과학 토론',
  },
  {
    name: 'language_learning',
    emoji: '🗣',
    index: 4,
    classificationName: 'learning_education',
    nameZHCN: '语言学习',
    nameZHTW: '語言學習',
    nameENUS: 'Language Learning',
    nameESES: 'Aprendizaje de Idiomas',
    nameFRFR: 'Apprentissage des Langues',
    nameRURU: 'Изучение Языков',
    nameJAJP: '言語学習',
    nameDEDE: 'Sprachenlernen',
    namePTBR: 'Aprendizado de Idiomas',
    nameKOKR: '언어 학습',
  },

  // 娱乐休闲主题
  {
    name: 'gaming_discussion',
    emoji: '🎮',
    index: 0,
    classificationName: 'entertainment_leisure',
    nameZHCN: '游戏讨论',
    nameZHTW: '遊戲討論',
    nameENUS: 'Gaming Discussion',
    nameESES: 'Discusión de Juegos',
    nameFRFR: 'Discussion Jeux',
    nameRURU: 'Обсуждение Игр',
    nameJAJP: 'ゲーム議論',
    nameDEDE: 'Spiele-Diskussion',
    namePTBR: 'Discussão de Jogos',
    nameKOKR: '게임 토론',
  },
  {
    name: 'movies_tv',
    emoji: '🎬',
    index: 1,
    classificationName: 'entertainment_leisure',
    nameZHCN: '影视剧集',
    nameZHTW: '影視劇集',
    nameENUS: 'Movies & TV Shows',
    nameESES: 'Películas y Series',
    nameFRFR: 'Films et Séries',
    nameRURU: 'Фильмы и Сериалы',
    nameJAJP: '映画とテレビ番組',
    nameDEDE: 'Filme & TV-Shows',
    namePTBR: 'Filmes e Séries',
    nameKOKR: '영화 및 TV 프로그램',
  },
  {
    name: 'music_sharing',
    emoji: '🎵',
    index: 2,
    classificationName: 'entertainment_leisure',
    nameZHCN: '音乐分享',
    nameZHTW: '音樂分享',
    nameENUS: 'Music Sharing',
    nameESES: 'Compartir Música',
    nameFRFR: 'Partage Musical',
    nameRURU: 'Музыкальный Обмен',
    nameJAJP: '音楽シェア',
    nameDEDE: 'Musik-Sharing',
    namePTBR: 'Compartilhamento Musical',
    nameKOKR: '음악 공유',
  },
  {
    name: 'photography_exchange',
    emoji: '📷',
    index: 3,
    classificationName: 'entertainment_leisure',
    nameZHCN: '摄影交流',
    nameZHTW: '攝影交流',
    nameENUS: 'Photography Exchange',
    nameESES: 'Intercambio Fotográfico',
    nameFRFR: 'Échange Photographique',
    nameRURU: 'Фотографический Обмен',
    nameJAJP: '写真交流',
    nameDEDE: 'Fotografie-Austausch',
    namePTBR: 'Intercâmbio Fotográfico',
    nameKOKR: '사진 교류',
  },
  {
    name: 'novels_comics',
    emoji: '📚',
    index: 4,
    classificationName: 'entertainment_leisure',
    nameZHCN: '小说漫画',
    nameZHTW: '小說漫畫',
    nameENUS: 'Novels & Comics',
    nameESES: 'Novelas y Cómics',
    nameFRFR: 'Romans et BD',
    nameRURU: 'Романы и Комиксы',
    nameJAJP: '小説と漫画',
    nameDEDE: 'Romane & Comics',
    namePTBR: 'Romances e Quadrinhos',
    nameKOKR: '소설 및 만화',
  },
  {
    name: 'anime_manga_world',
    emoji: '🎨',
    index: 5,
    classificationName: 'entertainment_leisure',
    nameZHCN: '二次元天地',
    nameZHTW: '二次元天地',
    nameENUS: 'Anime & Manga World',
    nameESES: 'Mundo del Anime y Manga',
    nameFRFR: 'Monde de l\'Anime et du Manga',
    nameRURU: 'Мир Аниме и Манги',
    nameJAJP: 'アニメとマンガの世界',
    nameDEDE: 'Anime & Manga Welt',
    namePTBR: 'Mundo do Anime e Mangá',
    nameKOKR: '애니메이션 및 만화 세계',
  },

  // 生活方式主题
  {
    name: 'travel_sharing',
    emoji: '✈️',
    index: 0,
    classificationName: 'lifestyle',
    nameZHCN: '旅游分享',
    nameZHTW: '旅遊分享',
    nameENUS: 'Travel Sharing',
    nameESES: 'Compartir Viajes',
    nameFRFR: 'Partage de Voyage',
    nameRURU: 'Путешествия',
    nameJAJP: '旅行シェア',
    nameDEDE: 'Reise-Sharing',
    namePTBR: 'Compartilhamento de Viagem',
    nameKOKR: '여행 공유',
  },
  {
    name: 'food_paradise',
    emoji: '🍳',
    index: 1,
    classificationName: 'lifestyle',
    nameZHCN: '美食天地',
    nameZHTW: '美食天地',
    nameENUS: 'Food Paradise',
    nameESES: 'Paraíso Gastronómico',
    nameFRFR: 'Paradis Culinaire',
    nameRURU: 'Кулинарный Рай',
    nameJAJP: 'グルメパラダイス',
    nameDEDE: 'Kulinarisches Paradies',
    namePTBR: 'Paraíso Gastronômico',
    nameKOKR: '음식 천국',
  },
  {
    name: 'fitness_health',
    emoji: '🏃',
    index: 2,
    classificationName: 'lifestyle',
    nameZHCN: '健身与健康',
    nameZHTW: '健身與健康',
    nameENUS: 'Fitness & Health',
    nameESES: 'Fitness y Salud',
    nameFRFR: 'Fitness et Santé',
    nameRURU: 'Фитнес и Здоровье',
    nameJAJP: 'フィットネスと健康',
    nameDEDE: 'Fitness & Gesundheit',
    namePTBR: 'Fitness e Saúde',
    nameKOKR: '피트니스 및 건강',
  },
  {
    name: 'home_decoration',
    emoji: '🏡',
    index: 3,
    classificationName: 'lifestyle',
    nameZHCN: '家居与装修',
    nameZHTW: '家居與裝修',
    nameENUS: 'Home & Decoration',
    nameESES: 'Hogar y Decoración',
    nameFRFR: 'Maison et Décoration',
    nameRURU: 'Дом и Декор',
    nameJAJP: 'ホームと装飾',
    nameDEDE: 'Zuhause & Dekoration',
    namePTBR: 'Casa e Decoração',
    nameKOKR: '홈 및 인테리어',
  },
  {
    name: 'pet_world',
    emoji: '🐶',
    index: 4,
    classificationName: 'lifestyle',
    nameZHCN: '宠物天地',
    nameZHTW: '寵物天地',
    nameENUS: 'Pet World',
    nameESES: 'Mundo de Mascotas',
    nameFRFR: 'Monde des Animaux',
    nameRURU: 'Мир Домашних Животных',
    nameJAJP: 'ペットの世界',
    nameDEDE: 'Haustier-Welt',
    namePTBR: 'Mundo dos Pets',
    nameKOKR: '반려동물 세계',
  },
  {
    name: 'fashion_beauty',
    emoji: '💄',
    index: 5,
    classificationName: 'lifestyle',
    nameZHCN: '穿搭与美妆',
    nameZHTW: '穿搭與美妝',
    nameENUS: 'Fashion & Beauty',
    nameESES: 'Moda y Belleza',
    nameFRFR: 'Mode et Beauté',
    nameRURU: 'Мода и Красота',
    nameJAJP: 'ファッションと美容',
    nameDEDE: 'Mode & Schönheit',
    namePTBR: 'Moda e Beleza',
    nameKOKR: '패션 및 뷰티',
  },

  // 职业发展主题
  {
    name: 'job_workplace',
    emoji: '🧑‍💼',
    index: 0,
    classificationName: 'career_development',
    nameZHCN: '求职与职场',
    nameZHTW: '求職與職場',
    nameENUS: 'Job Search & Workplace',
    nameESES: 'Búsqueda de Empleo y Lugar de Trabajo',
    nameFRFR: 'Recherche d\'Emploi et Lieu de Travail',
    nameRURU: 'Поиск Работы и Рабочее Место',
    nameJAJP: '就職活動と職場',
    nameDEDE: 'Jobsuche & Arbeitsplatz',
    namePTBR: 'Busca de Emprego e Local de Trabalho',
    nameKOKR: '구직 및 직장',
  },
  {
    name: 'finance_investment',
    emoji: '💸',
    index: 1,
    classificationName: 'career_development',
    nameZHCN: '理财投资',
    nameZHTW: '理財投資',
    nameENUS: 'Finance & Investment',
    nameESES: 'Finanzas e Inversión',
    nameFRFR: 'Finance et Investissement',
    nameRURU: 'Финансы и Инвестиции',
    nameJAJP: '金融と投資',
    nameDEDE: 'Finanzen & Investment',
    namePTBR: 'Finanças e Investimento',
    nameKOKR: '금융 및 투자',
  },
  {
    name: 'study_abroad_immigration',
    emoji: '🧳',
    index: 2,
    classificationName: 'career_development',
    nameZHCN: '留学与移民',
    nameZHTW: '留學與移民',
    nameENUS: 'Study Abroad & Immigration',
    nameESES: 'Estudiar en el Extranjero e Inmigración',
    nameFRFR: 'Études à l\'Étranger et Immigration',
    nameRURU: 'Обучение за Рубежом и Иммиграция',
    nameJAJP: '留学と移民',
    nameDEDE: 'Auslandsstudium & Immigration',
    namePTBR: 'Estudar no Exterior e Imigração',
    nameKOKR: '유학 및 이민',
  },
  {
    name: 'entrepreneurship_exchange',
    emoji: '📈',
    index: 3,
    classificationName: 'career_development',
    nameZHCN: '创业交流',
    nameZHTW: '創業交流',
    nameENUS: 'Entrepreneurship Exchange',
    nameESES: 'Intercambio de Emprendimiento',
    nameFRFR: 'Échange d\'Entrepreneuriat',
    nameRURU: 'Предпринимательский Обмен',
    nameJAJP: '起業交流',
    nameDEDE: 'Unternehmertum-Austausch',
    namePTBR: 'Intercâmbio de Empreendedorismo',
    nameKOKR: '창업 교류',
  },

  // 技术与创作主题
  {
    name: 'digital_hardware',
    emoji: '🖥️',
    index: 0,
    classificationName: 'technology_creation',
    nameZHCN: '数码硬件',
    nameZHTW: '數碼硬件',
    nameENUS: 'Digital Hardware',
    nameESES: 'Hardware Digital',
    nameFRFR: 'Matériel Numérique',
    nameRURU: 'Цифровое Оборудование',
    nameJAJP: 'デジタルハードウェア',
    nameDEDE: 'Digitale Hardware',
    namePTBR: 'Hardware Digital',
    nameKOKR: '디지털 하드웨어',
  },
  {
    name: 'mobile_apps',
    emoji: '📱',
    index: 1,
    classificationName: 'technology_creation',
    nameZHCN: '手机与APP',
    nameZHTW: '手機與APP',
    nameENUS: 'Mobile & Apps',
    nameESES: 'Móvil y Aplicaciones',
    nameFRFR: 'Mobile et Applications',
    nameRURU: 'Мобильные устройства и Приложения',
    nameJAJP: 'モバイルとアプリ',
    nameDEDE: 'Mobil & Apps',
    namePTBR: 'Mobile e Apps',
    nameKOKR: '모바일 및 앱',
  },
  {
    name: 'web_development',
    emoji: '🌐',
    index: 2,
    classificationName: 'technology_creation',
    nameZHCN: '网站开发',
    nameZHTW: '網站開發',
    nameENUS: 'Web Development',
    nameESES: 'Desarrollo Web',
    nameFRFR: 'Développement Web',
    nameRURU: 'Веб-разработка',
    nameJAJP: 'ウェブ開発',
    nameDEDE: 'Webentwicklung',
    namePTBR: 'Desenvolvimento Web',
    nameKOKR: '웹 개발',
  },
  {
    name: 'original_writing',
    emoji: '✍️',
    index: 3,
    classificationName: 'technology_creation',
    nameZHCN: '原创写作',
    nameZHTW: '原創寫作',
    nameENUS: 'Original Writing',
    nameESES: 'Escritura Original',
    nameFRFR: 'Écriture Originale',
    nameRURU: 'Оригинальное Письмо',
    nameJAJP: 'オリジナル執筆',
    nameDEDE: 'Originales Schreiben',
    namePTBR: 'Escrita Original',
    nameKOKR: '창작 글쓰기',
  },
  {
    name: 'design_painting',
    emoji: '🎨',
    index: 4,
    classificationName: 'technology_creation',
    nameZHCN: '设计与绘画',
    nameZHTW: '設計與繪畫',
    nameENUS: 'Design & Painting',
    nameESES: 'Diseño y Pintura',
    nameFRFR: 'Design et Peinture',
    nameRURU: 'Дизайн и Живопись',
    nameJAJP: 'デザインと絵画',
    nameDEDE: 'Design & Malerei',
    namePTBR: 'Design e Pintura',
    nameKOKR: '디자인 및 그림',
  },
  {
    name: 'diy_makers',
    emoji: '🧩',
    index: 5,
    classificationName: 'technology_creation',
    nameZHCN: 'DIY 与创客',
    nameZHTW: 'DIY 與創客',
    nameENUS: 'DIY & Makers',
    nameESES: 'DIY y Creadores',
    nameFRFR: 'DIY et Créateurs',
    nameRURU: 'DIY и Создатели',
    nameJAJP: 'DIYとメーカー',
    nameDEDE: 'DIY & Maker',
    namePTBR: 'DIY e Criadores',
    nameKOKR: 'DIY 및 메이커',
  },
];

async function main() {
  console.log('开始创建分类数据...');
  
  for (const classification of classifications) {
    await prisma.classification.create({
      data: classification,
    });
    console.log(`创建分类: ${classification.nameZHCN}`);
  }

  console.log('开始创建主题数据...');
  
  for (const topic of topics) {
    await prisma.topic.create({
      data: topic,
    });
    console.log(`创建主题: ${topic.nameZHCN}`);
  }

  console.log('数据创建完成！');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });